Update myaliases
更新 myaliases ，增加 proxy_on 函数并完善 gproxy 命令别名

diff --git a/etc/myaliases b/etc/myaliases
--- a/etc/myaliases
+++ b/etc/myaliases
@@ -61,7 +61,6 @@ alias shred=' shred -v'
 #   sleep 10; alert
 # You can use: make; alert to nofify you when compile complete
 alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
-alias gproxy=" export http_proxy='127.0.0.1:8087' https_proxy='127.0.0.1:8087' HTTP_PROXY='127.0.0.1:8087' HTTPS_PROXY='127.0.0.1:8087'"
 # }}}
 
 #   Pacman & Yaourt aliases {{{2
@@ -234,8 +233,57 @@ man() {
       man "$@"
 }
 # }}}
+
+#   彩色化 Man 帮助手册 {{{2
+function proxy_on() {
+  export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+
+  if (( $# > 0 )); then
+    # valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
+    # if [[ $valid != $@ ]]; then
+    #   >&2 echo "Invalid address"
+    #   return 1
+    # fi
+
+    export http_proxy="http://$1/"
+    export https_proxy=$http_proxy
+    export ftp_proxy=$http_proxy
+    export rsync_proxy=$http_proxy
+    echo "Proxy environment variable set."
+    return 0
+  fi
+
+  echo -n "username: "; read username
+  if [[ $username != "" ]]; then
+    echo -n "password: "
+    read -es password
+    local pre="$username:$password@"
+  fi
+
+  echo -n "server: "; read server
+  echo -n "port: "; read port
+  export http_proxy="http://$pre$server:$port/"
+  export https_proxy=$http_proxy
+  export ftp_proxy=$http_proxy
+  export rsync_proxy=$http_proxy
+  export HTTP_PROXY=$http_proxy
+  export HTTPS_PROXY=$http_proxy
+  export FTP_PROXY=$http_proxy
+  export RSYNC_PROXY=$http_proxy
+}
+
+function proxy_off(){
+  unset http_proxy
+  unset https_proxy
+  unset ftp_proxy
+  unset rsync_proxy
+  echo -e "Proxy environment variable removed."
+}
+
+alias gproxy=" proxy_on '127.0.0.1:8087'"
+# }}}
 # }}}
 
 # Vim Modeline {{{1
-# vim:ft=sh:fdm=marker:ai:et:sw=2:
+# vim:ft=sh:fdm=marker:ai:et:sts=2:sw=2:ts=2:
 # }}}
